["protostar.config"]
protostar_version = "0.7.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/controller/Controller.cairo"
]

["protostar.test"]
cairo-path = ["./lib/starknet_plugin_account/contracts"]
